services:
  grafana-loki:
    image: grafana/loki:2.8.2
    container_name: grafana-loki
    command: 
      - -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki:/etc/loki
      - loki-storage:/loki
    ports:
      - "3100:3100"
    networks:
      - grafana-net
    restart: unless-stopped

  grafana-alloy:
    image: grafana/alloy:v1.11.2
    container_name: grafana-alloy
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
       # Mount the log directory from host to container
      - /home/aatir/local_dev/misc/getMe/utils/logger/dump:/var/log/getme:ro
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "12345:12345"
    depends_on:
      - grafana-loki
    networks:
      - grafana-net
    restart: unless-stopped

volumes:
  loki-storage:

networks:
  grafana-net:
    driver: bridge
