version: '3.8'
services:
  get_me_store:
    build:
      context: .
      dockerfile: ContainerFile
      target: final
    container_name: get_me_store
    volumes:
      - getMeStoreData:/data/getMeStore
    restart: unless-stopped
volumes:
  getMeStoreData: