services:
  grafana-loki:
    image: grafana/loki:3.4.2
    container_name: grafana-loki
    command: 
      - -config.file=/etc/loki/config.yml
    volumes:
      - ./loki:/etc/loki
      - loki-storage:/loki
    ports:
      - "3100:3100"
    networks:
      - grafana-net
    restart: unless-stopped

  grafana-alloy:
    image: grafana/alloy:v1.11.2
    container_name: grafana-alloy
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
       # Mount the log directory from host to container
      - /tmp/getMeStore/dump:/var/log/getme:ro
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "12345:12345"
    depends_on:
      - grafana-loki
    networks:
      - grafana-net
    restart: unless-stopped
  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - grafana-loki
    networks:
      - grafana-net
    restart: unless-stopped

volumes:
  loki-storage:
  grafana-storage:

networks:
  grafana-net:
    driver: bridge
