services:
# Main application service
  get_me_store:
    build:
      context: .
      dockerfile: ContainerFile
      target: final
    container_name: get_me_store
    user: "${currentUserId}:${currentGroupId}"
    volumes:
      # Volume for persistent store data
      - get-me-store-data:/var/lib/getMeStore/dataDir
      # Bind mount the log directory from the host into the container.
      - log-dump:/tmp/getMeStore/dumpDir
      # Bind mount the socket directory from the host into the container.
      - /tmp/getMeStore/sockDir:/tmp/getMeStore/sockDir
    networks:
      - getme-wrapper-net
    restart: unless-stopped

# loki will serve as the log storage backend
  grafana-loki:
    image: grafana/loki:3.4.2
    container_name: grafana-loki
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./utils/logger/loki:/etc/loki
      - loki-storage:/loki
    ports:
      - "3100:3100"
    networks:
      - getme-wrapper-net
    restart: unless-stopped

# grafana-alloy will collect and forward logs to loki
  grafana-alloy:
    image: grafana/alloy:v1.11.2
    container_name: grafana-alloy
    volumes:
      - ./utils/logger/alloy/config.alloy:/etc/alloy/config.alloy
      # Bind mount to the host's log directory to read logs.
      - log-dump:/var/log/getme:ro
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "12345:12345"
    depends_on:
      get_me_store:
        condition: service_started
      grafana-loki:
        condition: service_started
    networks:
      - getme-wrapper-net
    restart: unless-stopped

# Grafana for log visualization
  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

      - ./utils/logger/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - grafana-loki
    networks:
      - getme-wrapper-net
    restart: unless-stopped

volumes:
  get-me-store-data:
  log-dump:
  loki-storage:
  grafana-storage:

networks:
  getme-wrapper-net:
    driver: bridge